// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateTransactions implements pgx.CopyFromSource.
type iteratorForBulkCreateTransactions struct {
	rows                 []BulkCreateTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].TxnDate,
		r.rows[0].Description,
		r.rows[0].Amount,
		r.rows[0].TxnType,
		r.rows[0].Category,
		r.rows[0].IsReviewed,
		r.rows[0].RawData,
	}, nil
}

func (r iteratorForBulkCreateTransactions) Err() error {
	return nil
}

func (q *Queries) BulkCreateTransactions(ctx context.Context, arg []BulkCreateTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"user_id", "txn_date", "description", "amount", "txn_type", "category", "is_reviewed", "raw_data"}, &iteratorForBulkCreateTransactions{rows: arg})
}
