// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores all parsed bank transactions from CSV uploads
type Transaction struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	TxnDate     pgtype.Date `json:"txn_date"`
	Description string      `json:"description"`
	// Negative for debit (money out), positive for credit (money in)
	Amount     pgtype.Numeric `json:"amount"`
	TxnType    string         `json:"txn_type"`
	Category   pgtype.Text    `json:"category"`
	IsReviewed bool           `json:"is_reviewed"`
	// Original CSV row for debugging and audit trail
	RawData   pgtype.Text        `json:"raw_data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// User accounts synchronized from Clerk authentication
type User struct {
	ID pgtype.UUID `json:"id"`
	// Clerk user ID (used for JWT validation)
	ClerkUserID string `json:"clerk_user_id"`
	// User email address
	Email string `json:"email"`
	// User full name (first + last)
	FullName  pgtype.Text        `json:"full_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
