// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateTransactionsParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	TxnDate     pgtype.Date    `json:"txn_date"`
	Description string         `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	TxnType     string         `json:"txn_type"`
	Category    pgtype.Text    `json:"category"`
	IsReviewed  bool           `json:"is_reviewed"`
	RawData     pgtype.Text    `json:"raw_data"`
}

const countCategorizedTransactions = `-- name: CountCategorizedTransactions :one
SELECT COUNT(*) FROM transactions
WHERE user_id = $1
  AND category IS NOT NULL
`

func (q *Queries) CountCategorizedTransactions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategorizedTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUncategorizedTransactions = `-- name: CountUncategorizedTransactions :one
SELECT COUNT(*) FROM transactions
WHERE user_id = $1
  AND category IS NULL
`

func (q *Queries) CountUncategorizedTransactions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUncategorizedTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserTransactions = `-- name: CountUserTransactions :one
SELECT COUNT(*) FROM transactions
WHERE user_id = $1
`

func (q *Queries) CountUserTransactions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    txn_date,
    description,
    amount,
    txn_type,
    category,
    is_reviewed,
    raw_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id
`

type CreateTransactionParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	TxnDate     pgtype.Date    `json:"txn_date"`
	Description string         `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	TxnType     string         `json:"txn_type"`
	Category    pgtype.Text    `json:"category"`
	IsReviewed  bool           `json:"is_reviewed"`
	RawData     pgtype.Text    `json:"raw_data"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.TxnDate,
		arg.Description,
		arg.Amount,
		arg.TxnType,
		arg.Category,
		arg.IsReviewed,
		arg.RawData,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxnDate,
		&i.Description,
		&i.Amount,
		&i.TxnType,
		&i.Category,
		&i.IsReviewed,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const deleteUserTransactions = `-- name: DeleteUserTransactions :exec
DELETE FROM transactions
WHERE user_id = $1
`

func (q *Queries) DeleteUserTransactions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTransactions, userID)
	return err
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id FROM transactions
WHERE user_id = $1
ORDER BY txn_date DESC
`

func (q *Queries) GetAllTransactions(ctx context.Context, userID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getAllTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TxnDate,
			&i.Description,
			&i.Amount,
			&i.TxnType,
			&i.Category,
			&i.IsReviewed,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategorizedTransactions = `-- name: GetCategorizedTransactions :many
SELECT id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id FROM transactions
WHERE user_id = $1
  AND category IS NOT NULL
ORDER BY txn_date DESC
LIMIT $2 OFFSET $3
`

type GetCategorizedTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetCategorizedTransactions(ctx context.Context, arg GetCategorizedTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getCategorizedTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TxnDate,
			&i.Description,
			&i.Amount,
			&i.TxnType,
			&i.Category,
			&i.IsReviewed,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id FROM transactions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxnDate,
		&i.Description,
		&i.Amount,
		&i.TxnType,
		&i.Category,
		&i.IsReviewed,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadID,
	)
	return i, err
}

const getTransactionStats = `-- name: GetTransactionStats :one
SELECT
    COUNT(*) AS total_count,
    COUNT(CASE WHEN category IS NOT NULL THEN 1 END) AS categorized_count,
    COUNT(CASE WHEN category IS NULL THEN 1 END) AS uncategorized_count,
    ROUND(
        CAST(COUNT(CASE WHEN category IS NOT NULL THEN 1 END) AS DECIMAL) /
        NULLIF(COUNT(*), 0) * 100,
        2
    ) AS accuracy_percent
FROM transactions
WHERE user_id = $1
`

type GetTransactionStatsRow struct {
	TotalCount         int64          `json:"total_count"`
	CategorizedCount   int64          `json:"categorized_count"`
	UncategorizedCount int64          `json:"uncategorized_count"`
	AccuracyPercent    pgtype.Numeric `json:"accuracy_percent"`
}

func (q *Queries) GetTransactionStats(ctx context.Context, userID pgtype.UUID) (GetTransactionStatsRow, error) {
	row := q.db.QueryRow(ctx, getTransactionStats, userID)
	var i GetTransactionStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.CategorizedCount,
		&i.UncategorizedCount,
		&i.AccuracyPercent,
	)
	return i, err
}

const getTransactionsByCategory = `-- name: GetTransactionsByCategory :many
SELECT id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id FROM transactions
WHERE user_id = $1
  AND category = $2
ORDER BY txn_date DESC
LIMIT $3 OFFSET $4
`

type GetTransactionsByCategoryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Category pgtype.Text `json:"category"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) GetTransactionsByCategory(ctx context.Context, arg GetTransactionsByCategoryParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByCategory,
		arg.UserID,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TxnDate,
			&i.Description,
			&i.Amount,
			&i.TxnType,
			&i.Category,
			&i.IsReviewed,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByDateRange = `-- name: GetTransactionsByDateRange :many
SELECT id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id FROM transactions
WHERE user_id = $1
  AND txn_date BETWEEN $2 AND $3
ORDER BY txn_date DESC
`

type GetTransactionsByDateRangeParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TxnDate   pgtype.Date `json:"txn_date"`
	TxnDate_2 pgtype.Date `json:"txn_date_2"`
}

func (q *Queries) GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByDateRange, arg.UserID, arg.TxnDate, arg.TxnDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TxnDate,
			&i.Description,
			&i.Amount,
			&i.TxnType,
			&i.Category,
			&i.IsReviewed,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUncategorizedTransactions = `-- name: GetUncategorizedTransactions :many
SELECT id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id FROM transactions
WHERE user_id = $1
  AND category IS NULL
ORDER BY txn_date DESC
LIMIT $2 OFFSET $3
`

type GetUncategorizedTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetUncategorizedTransactions(ctx context.Context, arg GetUncategorizedTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUncategorizedTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TxnDate,
			&i.Description,
			&i.Amount,
			&i.TxnType,
			&i.Category,
			&i.IsReviewed,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id FROM transactions
WHERE user_id = $1
ORDER BY txn_date DESC
LIMIT $2 OFFSET $3
`

type GetUserTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetUserTransactions(ctx context.Context, arg GetUserTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUserTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TxnDate,
			&i.Description,
			&i.Amount,
			&i.TxnType,
			&i.Category,
			&i.IsReviewed,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET description = COALESCE($2, description),
    amount = COALESCE($3, amount),
    txn_type = COALESCE($4, txn_type),
    category = COALESCE($5, category),
    is_reviewed = COALESCE($6, is_reviewed),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id
`

type UpdateTransactionParams struct {
	ID          pgtype.UUID    `json:"id"`
	Description string         `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	TxnType     string         `json:"txn_type"`
	Category    pgtype.Text    `json:"category"`
	IsReviewed  bool           `json:"is_reviewed"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Description,
		arg.Amount,
		arg.TxnType,
		arg.Category,
		arg.IsReviewed,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxnDate,
		&i.Description,
		&i.Amount,
		&i.TxnType,
		&i.Category,
		&i.IsReviewed,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadID,
	)
	return i, err
}

const updateTransactionCategory = `-- name: UpdateTransactionCategory :one
UPDATE transactions
SET category = $2,
    is_reviewed = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, txn_date, description, amount, txn_type, category, is_reviewed, raw_data, created_at, updated_at, upload_id
`

type UpdateTransactionCategoryParams struct {
	ID         pgtype.UUID `json:"id"`
	Category   pgtype.Text `json:"category"`
	IsReviewed bool        `json:"is_reviewed"`
}

func (q *Queries) UpdateTransactionCategory(ctx context.Context, arg UpdateTransactionCategoryParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionCategory, arg.ID, arg.Category, arg.IsReviewed)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxnDate,
		&i.Description,
		&i.Amount,
		&i.TxnType,
		&i.Category,
		&i.IsReviewed,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadID,
	)
	return i, err
}
